name: evolve
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.5.2
      - airportsdata==20250224
      - antlr4-python3-runtime==4.7.2
      - anyio==4.11.0
      - audioread==3.0.1
      - av==14.2.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - clip==1.0
      - codetiming==1.4.0
      - compressed-tensors==0.9.2
      - configs==3.0.3
      - dashscope==1.23.0
      - datasets==3.5.1
      - decord==0.6.0
      - deepspeed==0.16.4
      - diffusers==0.36.0.dev0
      - docstring-parser==0.16
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - fire==0.7.0
      - flash-attn==2.7.0.post2
      - flask==3.1.0
      - fonttools==4.56.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.66.0
      - gradio==5.21.0
      - gradio-client==1.7.2
      - groovy==0.1.2
      - grpcio==1.70.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - interegular==0.3.3
      - isort==6.0.1
      - itsdangerous==2.2.0
      - jieba==0.42.1
      - jiter==0.8.2
      - jsonlines==4.0.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - latex2sympy2==1.9.1
      - latex2sympy2-extended==1.0.6
      - levenshtein==0.27.1
      - librosa==0.11.0
      - liger-kernel==0.5.6
      - linkify-it-py==2.0.3
      - llamafactory==0.9.3.dev0
      - llguidance==0.7.13
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - lmdeploy==0.7.2.post1
      - loguru==0.7.3
      - loralib==0.1.2
      - markdown==3.7
      - markupsafe==2.1.5
      - math-verify==0.5.2
      - mathruler==0.1.0
      - matplotlib==3.10.1
      - mdit-py-plugins==0.4.2
      - memray==1.17.0
      - mistral-common==1.5.4
      - mm-eureka==0.6.2
      - mmengine-lite==0.10.7
      - modelscope==1.22.3
      - msgspec==0.19.0
      - nanobind==2.6.1
      - nltk==3.9.1
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.61.1
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - optimum==1.24.0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - partial-json-parser==0.2.1.1.post5
      - peft==0.17.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.2.1
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - py-spy==0.4.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycocotools==2.0.8
      - pycountry==24.6.1
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pylatexenc==2.10
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pytest==8.3.4
      - python-dotenv==1.0.1
      - python-levenshtein==0.27.1
      - pytz==2025.1
      - pyyaml==6.0.3
      - pyzmq==26.2.1
      - qwen-vl-utils==0.0.10
      - rapidfuzz==3.12.2
      - ray==2.43.0
      - referencing==0.36.2
      - requests==2.32.5
      - rich-toolkit==0.13.2
      - rouge-chinese==1.0.3
      - rpds-py==0.22.3
      - rsa==4.9
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - setuptools==75.1.0
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sse-starlette==2.2.1
      - starlette==0.46.1
      - sty==1.0.6
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensordict==0.6.2
      - textual==3.0.1
      - timm==1.0.14
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.2.0
      - trl==0.9.6
      - typer==0.15.2
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.0
      - tyro==0.8.14
      - tzdata==2025.1
      - uc-micro-py==1.0.3
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - verl==0.2.0.dev0
      - virtualenv==20.29.2
      - vllm==0.8.3
      - wandb==0.18.3
      - websockets==14.2
      - werkzeug==3.1.3
      - wheel==0.44.0
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.17
      - zipp==3.21.0
